### ISSUE TITLE
start the glossary section

### ISSUE THREAD

**Issue by billspat** [IBEEM-MSU/ibeem-collaborative-coding#16]
this can be an ad-hoc issue to collect items to put into the glossary and committed to the main branch as needed.   

starting list of random things! 

- repo
- remote
- git flow
- sub-repo
- issue
- PR
- commit
- markdown
- github flavored-markdown (GFM)
- branch
- squashed commits
- commit hash  (nickname for the git commit SHA-1 checksum value)

**Comment by billspat** [comment]
should the glossary be it's own section so it can grow?

**Comment by kellykapsar** [comment]
> should the glossary be it's own section so it can grow?

I think that's a good idea. We can put it at the end before the works cited and people can reference as needed.

**Comment by billspat** [comment]
additional glossary items: 

 - changeset https://en.wikipedia.org/wiki/Changeset
 - source tree or "graph": topology of branches eg from `git log --graph`
 -
